services:
  back:
    build:
      context: back
      dockerfile: Dockerfile
      args:
        APP_DIR: /myapp
    command: >
      bash -c "
        rm -f tmp/pids/server.pid &&
        bundle install --path vendor/bundle &&
        bundle exec rails db:migrate &&
        bundle exec rails s
      "
    environment:
      RAILS_ENV: development
      DB_HOST: ${DB_HOST}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./back:/myapp
    ports:
      - 3000:3000
    depends_on:
      - db
    logging:
      driver: json-file
      options:
        max-size: 5m
        max-file: 20

  # データベース
  db:
    build:
      context: db
      dockerfile: Dockerfile
    environment:
      TZ: Asia/Tokyo
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
    ports:
      - 5432:5432
    volumes:
      - ./db/data:/var/lib/postgresql/data
      # - ./db/init:/docker-entrypoint-initdb.d # 初期データ投入用
    logging:
      driver: json-file
      options:
        max-size: 5m
        max-file: 20
