services:
  front:
    build:
      context: front
      dockerfile: Dockerfile
      args:
        APP_DIR: /myapp
    environment:
      TZ: Asia/Tokyo
      LANG: ja_JP.UTF-8
    command: bash -c "npm install && ng serve --host 0.0.0.0 --port 80"
    ports:
      - ${HTTP_PORT}:80
    volumes:
      - ./front:/myapp
    logging:
      driver: json-file
      options:
        max-size: 5m
        max-file: 20

  back:
    build:
      context: back
      dockerfile: Dockerfile
      args:
        APP_DIR: /myapp
    command: >
      bash -c "
        rm -f tmp/pids/server.pid &&
        bundle install &&
        bundle exec rails db:migrate &&
        bundle exec rails s -e development
      "
    environment:
      RAILS_ENV: development
      DB_HOST: ${DB_HOST}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      SESSION_TIMEOUT: 8 # SSOではなくログイン画面を使用したときのセッション時間
      TZ: Asia/Tokyo
      LANG: ja_JP.UTF-8
    volumes:
      - ./back:/myapp
    ports:
      - 3000:3000
    depends_on:
      - db
    logging:
      driver: json-file
      options:
        max-size: 5m
        max-file: 20

  # データベース
  db:
    image: postgres:16.3
    environment:
      TZ: Asia/Tokyo
      postgres_db: ${DB_DATABASE}
      postgres_user: ${DB_USER}
      postgres_password: ${DB_PASSWORD}
      postgres_initdb_args: "--encoding=UTF-8 --locale=C"
    ports:
      - 5432:5432
    volumes:
      - ./db/data:/var/lib/postgresql/data
      # - ./db/init:/docker-entrypoint-initdb.d # 初期データ投入用
    logging:
      driver: json-file
      options:
        max-size: 5m
        max-file: 20
